### ISSUE TITLE
NPE when running under jdk 10

### ISSUE THREAD

**Issue by glenn-mcgregor** [zaro/pdf-metadata-editor#14]
[C:\Program Files\PdfMetadataEditor][info] Module Name: C:\Program Files\PdfMetadataEditor\PdfMetadataEditor.exe
[info] Module INI: C:\Program Files\PdfMetadataEditor\PdfMetadataEditor.ini
[info] Module Dir: C:\Program Files\PdfMetadataEditor\
[info] INI Dir: C:\Program Files\PdfMetadataEditor\
[info] Configured vm.location: c:\java\jdk-10.0.1\bin\server\jvm.dll
[info] Found VM: c:\java\jdk-10.0.1\bin\server\jvm.dll
[info] Expanding Classpath: pdf-metadata-edit-2.2.2.jar
[info] Generated Classpath: C:\Program Files\PdfMetadataEditor\pdf-metadata-edit-2.2.2.jar
[info] VM Args:
[info] vmarg.0=-DlauncherDDE=yes
[info] vmarg.1=-Djava.class.path=C:\Program Files\PdfMetadataEditor\pdf-metadata-edit-2.2.2.jar
[info] Registering natives for Native class
[warn] Could not find Native class
[info] Initializing DDE
java.lang.NullPointerException
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
        at pmedit.PDFMetadataEditWindow.initialize(PDFMetadataEditWindow.java:390)
        at pmedit.PDFMetadataEditWindow.<init>(PDFMetadataEditWindow.java:55)
        at pmedit.Main.executeCommandSwingWorker(Main.java:132)
        at pmedit.Main$CommandsExecutor.process(Main.java:62)
        at java.desktop/javax.swing.SwingWorker$3.run(SwingWorker.java:414)
        at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:834)
        at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:844)
        at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
        at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
^C
[C:\Program Files\PdfMetadataEditor][info] Application exited (130).

**Comment by slahn** [comment]
The crash is at PDFMetadataEditWindow:390: `.getResource("/com/sun/java/swing/plaf/windows/icons/FloppyDrive.gif")));`. Appearently that resource isn't found under JRE 10.

Just commenting out that line makes the program start.

**Comment by zaro** [comment]
@slahn yes, this is an easy fix,thank you for pointing it out. I haven't released it as I cannot get the installer working JRE 10.

**Comment by arend-von-reinersdorff** [comment]
Just stumbled over this with JDK 11. (For now I managed with JDK 8)

@zaro Any chance of a release with the fix?

Also, thanks for this helpful tool :-)

**Comment by arend-von-reinersdorff** [comment]
No longer an issue with version 3.1.1. Thanks.
