### ISSUE TITLE
On Windows, it says "failed to find Java VM"

### ISSUE THREAD

**Issue by ComFreek** [zaro/pdf-metadata-editor#21]
I downloaded the portable installer (http://broken-by.me/download/pme-extract-run-zip/) and tried double-clicking `PdfMetadataEditor64.exe` in Windows Explorer. It shows "Failed to find Java VM".
The same error is shown upon running the CLI executables.

And if I invoke the .jar using Java manually, I get an exception:
```bash
$> java -jar pdf-metadata-edit-2.2.2.jar
java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
        at pmedit.PDFMetadataEditWindow.initialize(PDFMetadataEditWindow.java:390)
        at pmedit.PDFMetadataEditWindow.<init>(PDFMetadataEditWindow.java:55)
        at pmedit.Main.executeCommandSwingWorker(Main.java:132)
        at pmedit.Main$CommandsExecutor.process(Main.java:62)
        at java.desktop/javax.swing.SwingWorker$3.run(SwingWorker.java:423)
        at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
        at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
        at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
        at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## My System

Windows 10 Pro 64-Bit, Build 19041.1052.

```bash
$> where.exe java
C:\Program Files\OpenJDK\jdk-16.0.1\bin\java.exe

$> java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by zaro** [comment]
Unfortunately, only Java 8 is supported ATM. Ironically it's precisely
windows support that is the problem to move to newer Java version.

**Comment by aaronamm** [comment]
I got the same issue "failed to find Java VM"
I use OpenJDK 8 but it does not work for me as well.
```ps
PS C:\Users\aaron\Documents> where.exe java
C:\Program Files\OpenJDK\openjdk-8u312-b07\bin\java.exe
PS C:\Users\aaron\Documents> java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```
Here is my OS version:
10.0.19043.0 Microsoft Windows NT 10.0.19043.0

**Comment by zaro** [comment]
There is a new version 3.0.0  with all the requirement bundled, so it should work.
